APT::FTPArchive::Release {
  Origin "Polina's Repo";
  Label "AAlx";
  Suite "stable";
  Version "1.3";
  Codename "aalx-repo";
  Architectures "iphoneos-arm";
  Components "main";
  Description "iOS 6 development tools";
};
